#!/bin/bash

EXCLUDE=(code.google.com github.com golang.org labix.org gopkg.in launchpad.net)
PACKAGES=(`go list ./...`)

# Drop an existing test database if it exists, then recreate it.
mongo rectest --eval "db.dropDatabase()"
mongorestore test/db/ -d rectest

# For each package, check to see whether it's a package that needs
# to be tested. If so, run `go test <package_name>`
for pack in ${PACKAGES[*]}; do
	valid=true
	for ex in ${EXCLUDE[*]}; do
		if [[ ${pack} == ${ex}* ]]; then
			valid=false
		fi
	done
	
	if [ $valid == true ]; then
		echo $pack
#		go test $pack
	fi
done
